---
title: "LP DAAC Data Resources"
---

This web-book is a place to find resources that demonstrate how to use [LP DAAC](https://lpdaac.usgs.gov/) tools, services, and data, as well as view content presented at previous LP DAAC webinars and workshops. The repository and web-book are still under active development. All notebooks and scripts should be functional, however, changes or additions may be made.

## Available Resources

In addition to this web-book, Github Repositories containing examples of working with various datasets are available. Eventually we plan to integrate all of those notebooks into this web-book. In the meantime, some general resources can be found in the respotitories listed in the following table. Additionally, there is a separate [web-book](https://nasa.github.io/VITALS/) for the [VSWIR Imaging and Thermal Applications, Learning, and Science (VITALS) Repository](https://github.com/nasa/VITALS), which focuses on the compounded benefits of using VSWIR and TIR data together.

Content include in this repository are listed below.  

| Repository Contents | Type | Summary |  
|----|-----|----|  
| **[Data_Discovery_CMR_API_Request.ipynb](/python/tutorials/Data_Discovery_CMR_API_Request.ipynb)** | Jupyter Notebook | Demonstrates how to search for Earthdata data collections and granules using CMR API and Request Python package|
| **[Data_Discovery_CMR_API_Bulk_Query.ipynb](/python/tutorials/Data_Discovery_CMR_API_Bulk_Query.ipynb)** | Jupyter Notebook | Demonstrates how to search and extract data URLs for an entire collection using Python's `asyncio` package|
| **[bulk_download_using_curl.md](/guides/bulk_download_using_curl.md)** | Markdown | Demonstrates how to bulk download LP DAAC data using Curl from command line |
| **[bulk_download_using_wget.md](/guides/bulk_download_using_wget.md)** | Markdown | Demonstrates how to bulk download LP DAAC data using Wget from command line |

The other guides, tutorials, how-tos and scripts can be accessed in our mission specific repositories. 

| Resource Repository | Summary | Services and Tools |
|----|-----|----|
|[AppEEARS Data Resources](https://github.com/nasa/AppEEARS-Data-Resources) |How to use the Application for Extracting and Exploring Analysis Ready Samples (AppEEARS) |Tutorials, AppEEARS API, Direct S3 Access |
|[EMIT Data](https://github.com/nasa/EMIT-Data-Resources) |How to find, access, and work with EMIT data (Earth Surface Mineral Dust Source Investigation)|Tutorials, Scripts, Direct S3 Access |
|[GEDI Data](https://github.com/nasa/GEDI-Data-Resources) |How to find, access, and work with GEDI data (Global Ecosystem Dynamics Investigation)|Tutorials |
|[HLS Data](https://github.com/nasa/HLS-Data-Resources)|How to find, access, and work with HLS data (Harmonized Landsat Sentinel-2)|Tutorials, Scripts, Direct S3 Access|
|[ECOSTRESS Data](https://github.com/nasa/ECOSTRESS-Data-Resources)|How to find, access, and work with ECOSTRESS data (The ECOsystem Spaceborne Thermal Radiometer Experiment on Space Station)|Tutorials, Scripts, Direct S3 Access|

---

## Contact Info  

Email: <LPDAAC@usgs.gov>  
Voice: +1-866-573-3222  
Organization: Land Processes Distributed Active Archive Center (LP DAAC)¹  
Website: <https://lpdaac.usgs.gov/>  
Date last modified: 06-24-2024  

¹Work performed under USGS contract 140G0121D0001 for NASA contract NNG14HH33I. 
